version: '3'
services:
  session1:
    build: '.'
    environment:
      - APP_ID=session1
    ports:
      - '3000:3000'

  session2:
    build: '.'
    environment:
      - APP_ID=session2
    ports:
      - '3001:3000'
  nginx:
    image: nginx:latest
    ports:
      - '8080:8080'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - session1
      - session2
